// <auto-generated />
using System;
using Degerli.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Degerli.Persistence.Migrations
{
    [DbContext(typeof(DegerliDbContext))]
    partial class DegerliDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Degerli.Persistence.Entities.ApplicationRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("LanguagePref")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("tr")
                        .HasColumnName("language_pref");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.BusinessDescription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<DateTimeOffset?>("LastReviewedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_reviewed_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<string>("SourceRefsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("source_refs_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TextEn")
                        .HasColumnType("text")
                        .HasColumnName("text_en");

                    b.Property<string>("TextTr")
                        .HasColumnType("text")
                        .HasColumnName("text_tr");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_business_descriptions");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_business_descriptions_instrument_id");

                    b.ToTable("business_descriptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_business_descriptions_published_texts", "status <> 'published' OR (text_tr IS NOT NULL AND text_en IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.ConsentRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("ConsentedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consented_at");

                    b.Property<string>("NoticeVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notice_version");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("UserRefHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_ref_hash");

                    b.HasKey("Id")
                        .HasName("pk_consent_records");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_consent_records_user_id");

                    b.ToTable("consent_records", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.CorporateAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("ActionDate")
                        .HasColumnType("date")
                        .HasColumnName("action_date");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.Property<string>("TermsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("terms_json");

                    b.HasKey("Id")
                        .HasName("pk_corporate_actions");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_corporate_actions_instrument_id");

                    b.ToTable("corporate_actions", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.CoverageMetadata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("AvailableFrom")
                        .HasColumnType("date")
                        .HasColumnName("available_from");

                    b.Property<DateOnly?>("AvailableTo")
                        .HasColumnType("date")
                        .HasColumnName("available_to");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_type");

                    b.Property<string>("FundId")
                        .HasColumnType("text")
                        .HasColumnName("fund_id");

                    b.Property<long?>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_coverage_metadata");

                    b.ToTable("coverage_metadata", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.DailyPrice", b =>
                {
                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("date")
                        .HasColumnName("price_date");

                    b.Property<decimal?>("CloseAdjusted")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("close_adjusted");

                    b.Property<decimal>("CloseRaw")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("close_raw");

                    b.Property<decimal?>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("high");

                    b.Property<decimal?>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("low");

                    b.Property<decimal?>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("open");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("InstrumentId", "PriceDate")
                        .HasName("pk_daily_prices");

                    b.ToTable("daily_prices", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.DcfBaseline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("BuildDate")
                        .HasColumnType("date")
                        .HasColumnName("build_date");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("params_json");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_dcf_baselines");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_dcf_baselines_instrument_id");

                    b.ToTable("dcf_baselines", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.DcfScenario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("params_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_dcf_scenarios");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_dcf_scenarios_instrument_id");

                    b.HasIndex("UserId", "InstrumentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_dcf_scenarios_user_id_instrument_id_name");

                    b.ToTable("dcf_scenarios", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.DerivedMetric", b =>
                {
                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<string>("MetricCode")
                        .HasColumnType("text")
                        .HasColumnName("metric_code");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("computed_at");

                    b.Property<bool>("IsAdjusted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_adjusted");

                    b.Property<bool>("IsRested")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rested");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("value");

                    b.Property<int?>("WindowYears")
                        .HasColumnType("integer")
                        .HasColumnName("window_years");

                    b.HasKey("InstrumentId", "MetricCode", "AsOfDate")
                        .HasName("pk_derived_metrics");

                    b.ToTable("derived_metrics", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.Dividend", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmountPerShare")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount_per_share");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("ExDate")
                        .HasColumnType("date")
                        .HasColumnName("ex_date");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<DateOnly?>("PayDate")
                        .HasColumnType("date")
                        .HasColumnName("pay_date");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.HasKey("Id")
                        .HasName("pk_dividends");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_dividends_instrument_id");

                    b.ToTable("dividends", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.FinLineItem", b =>
                {
                    b.Property<long>("StatementId")
                        .HasColumnType("bigint")
                        .HasColumnName("statement_id");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value");

                    b.HasKey("StatementId", "ItemCode")
                        .HasName("pk_fin_line_items");

                    b.ToTable("fin_line_items", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.FinancialStatement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<DateOnly>("PeriodEndDate")
                        .HasColumnType("date")
                        .HasColumnName("period_end_date");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period_type");

                    b.Property<DateOnly?>("PublishedAt")
                        .HasColumnType("date")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<DateOnly?>("RestatementDate")
                        .HasColumnType("date")
                        .HasColumnName("restatement_date");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.Property<string>("StatementType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement_type");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_financial_statements");

                    b.HasIndex("InstrumentId", "PeriodType", "PeriodEndDate", "StatementType", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_financial_statements_instrument_id_period_type_period_end_d");

                    b.ToTable("financial_statements", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.Fund", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("FundType")
                        .HasColumnType("text")
                        .HasColumnName("fund_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Code")
                        .HasName("pk_funds");

                    b.ToTable("funds", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.FundHolding", b =>
                {
                    b.Property<string>("FundId")
                        .HasColumnType("text")
                        .HasColumnName("fund_id");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<long?>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<string>("NameRaw")
                        .HasColumnType("text")
                        .HasColumnName("name_raw");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.Property<decimal?>("Units")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("units");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("weight");

                    b.HasKey("FundId", "AsOfDate", "LineNo")
                        .HasName("pk_fund_holdings");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_fund_holdings_instrument_id");

                    b.ToTable("fund_holdings", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.FundNav", b =>
                {
                    b.Property<string>("FundId")
                        .HasColumnType("text")
                        .HasColumnName("fund_id");

                    b.Property<DateOnly>("NavDate")
                        .HasColumnType("date")
                        .HasColumnName("nav_date");

                    b.Property<decimal>("NavValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("nav_value");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.HasKey("FundId", "NavDate")
                        .HasName("pk_fund_navs");

                    b.ToTable("fund_navs", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.FundPerformance", b =>
                {
                    b.Property<string>("FundId")
                        .HasColumnType("text")
                        .HasColumnName("fund_id");

                    b.Property<string>("Period")
                        .HasColumnType("text")
                        .HasColumnName("period");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<decimal?>("ReturnValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("return_value");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.HasKey("FundId", "Period", "AsOfDate")
                        .HasName("pk_fund_performances");

                    b.ToTable("fund_performances", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.IndexConstituent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<long>("IndexId")
                        .HasColumnType("bigint")
                        .HasColumnName("index_id");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.HasKey("Id")
                        .HasName("pk_index_constituents");

                    b.HasIndex("IndexId")
                        .HasDatabaseName("ix_index_constituents_index_id");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_index_constituents_instrument_id");

                    b.ToTable("index_constituents", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.IndexLevel", b =>
                {
                    b.Property<long>("IndexId")
                        .HasColumnType("bigint")
                        .HasColumnName("index_id");

                    b.Property<DateOnly>("LevelDate")
                        .HasColumnType("date")
                        .HasColumnName("level_date");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("close");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.HasKey("IndexId", "LevelDate")
                        .HasName("pk_index_levels");

                    b.ToTable("index_levels", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.IngestRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("finished_at");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_code");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("StatsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("stats_json");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_ingest_runs");

                    b.ToTable("ingest_runs", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.Instrument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("DelistingDate")
                        .HasColumnType("date")
                        .HasColumnName("delisting_date");

                    b.Property<string>("Isin")
                        .HasColumnType("text")
                        .HasColumnName("isin");

                    b.Property<DateOnly?>("ListingDate")
                        .HasColumnType("date")
                        .HasColumnName("listing_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<long?>("SectorId")
                        .HasColumnType("bigint")
                        .HasColumnName("sector_id");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("ix_instruments_sector_id");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_instruments_symbol");

                    b.ToTable("instruments", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.KapDisclosure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisclosureType")
                        .HasColumnType("text")
                        .HasColumnName("disclosure_type");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("text")
                        .HasColumnName("document_path");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<DateOnly?>("PublishDate")
                        .HasColumnType("date")
                        .HasColumnName("publish_date");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_kap_disclosures");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_kap_disclosures_instrument_id");

                    b.ToTable("kap_disclosures", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.MacroSeries", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Cadence")
                        .HasColumnType("text")
                        .HasColumnName("cadence");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_tr");

                    b.Property<string>("SourceName")
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Code")
                        .HasName("pk_macro_series");

                    b.ToTable("macro_series", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.MacroValue", b =>
                {
                    b.Property<string>("SeriesCode")
                        .HasColumnType("text")
                        .HasColumnName("series_code");

                    b.Property<DateOnly>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("value");

                    b.HasKey("SeriesCode", "ValueDate", "RecordedAt")
                        .HasName("pk_macro_values");

                    b.ToTable("macro_values", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.MarketIndex", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_tr");

                    b.HasKey("Id")
                        .HasName("pk_indices");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_indices_code");

                    b.ToTable("indices", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.MarketSnapshot", b =>
                {
                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<DateOnly>("AsOfTradingDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_trading_date");

                    b.Property<int?>("BreadthAdvancing")
                        .HasColumnType("integer")
                        .HasColumnName("breadth_advancing");

                    b.Property<int?>("BreadthDeclining")
                        .HasColumnType("integer")
                        .HasColumnName("breadth_declining");

                    b.Property<int?>("BreadthUnchanged")
                        .HasColumnType("integer")
                        .HasColumnName("breadth_unchanged");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("computed_at");

                    b.Property<string>("GainersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("gainers_json");

                    b.Property<string>("LosersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("losers_json");

                    b.Property<decimal?>("MarketDivYield")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("market_div_yield");

                    b.Property<decimal?>("MarketPe")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("market_pe");

                    b.Property<int?>("MarketPeExcludedCount")
                        .HasColumnType("integer")
                        .HasColumnName("market_pe_excluded_count");

                    b.Property<string>("SectorPerfJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("sector_perf_json");

                    b.Property<decimal?>("VolumeTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("volume_total");

                    b.Property<decimal?>("Xu100ChangePct")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("xu100_change_pct");

                    b.Property<decimal?>("Xu100Level")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("xu100_level");

                    b.Property<decimal?>("Xu30ChangePct")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("xu30_change_pct");

                    b.Property<decimal?>("Xu30Level")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("xu30_level");

                    b.HasKey("SnapshotDate")
                        .HasName("pk_market_snapshots");

                    b.ToTable("market_snapshots", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.MetricCatalogEntry", b =>
                {
                    b.Property<string>("MetricCode")
                        .HasColumnType("text")
                        .HasColumnName("metric_code");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionTr")
                        .HasColumnType("text")
                        .HasColumnName("description_tr");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("family");

                    b.Property<bool>("IsGrowthCagr")
                        .HasColumnType("boolean")
                        .HasColumnName("is_growth_cagr");

                    b.Property<bool>("IsScreenable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_screenable");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<string>("LabelTr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_tr");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("MetricCode")
                        .HasName("pk_metric_catalog");

                    b.ToTable("metric_catalog", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.QuarantinedFact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_code");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset>("QuarantinedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("quarantined_at");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolution_note");

                    b.Property<string>("SourceRef")
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_quarantined_facts");

                    b.ToTable("quarantined_facts", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.SavedScreen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("criteria_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_screens");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_saved_screens_user_id_name");

                    b.ToTable("saved_screens", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.Sector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_tr");

                    b.Property<long?>("ParentSectorId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_sector_id");

                    b.HasKey("Id")
                        .HasName("pk_sectors");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sectors_code");

                    b.HasIndex("ParentSectorId")
                        .HasDatabaseName("ix_sectors_parent_sector_id");

                    b.ToTable("sectors", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.SectorMetricMedian", b =>
                {
                    b.Property<long>("SectorId")
                        .HasColumnType("bigint")
                        .HasColumnName("sector_id");

                    b.Property<string>("MetricCode")
                        .HasColumnType("text")
                        .HasColumnName("metric_code");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("computed_at");

                    b.Property<int?>("ExcludedCount")
                        .HasColumnType("integer")
                        .HasColumnName("excluded_count");

                    b.Property<bool>("IsAdjusted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_adjusted");

                    b.Property<decimal?>("MedianValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("median_value");

                    b.Property<int?>("PeerCount")
                        .HasColumnType("integer")
                        .HasColumnName("peer_count");

                    b.HasKey("SectorId", "MetricCode", "AsOfDate")
                        .HasName("pk_sector_metric_medians");

                    b.ToTable("sector_metric_medians", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.BusinessDescription", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_business_descriptions_instruments_instrument_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.ConsentRecord", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_consent_records_asp_net_users_user_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.CorporateAction", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_corporate_actions_instruments_instrument_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.DailyPrice", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_prices_instruments_instrument_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.DcfBaseline", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dcf_baselines_instruments_instrument_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.DcfScenario", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dcf_scenarios_instruments_instrument_id");

                    b.HasOne("Degerli.Persistence.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dcf_scenarios_asp_net_users_user_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.DerivedMetric", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_derived_metrics_instruments_instrument_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.Dividend", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dividends_instruments_instrument_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.FinLineItem", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.FinancialStatement", null)
                        .WithMany()
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fin_line_items_financial_statements_statement_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.FinancialStatement", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_statements_instruments_instrument_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.FundHolding", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Fund", null)
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fund_holdings_funds_fund_id");

                    b.HasOne("Degerli.Persistence.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fund_holdings_instruments_instrument_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.FundNav", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Fund", null)
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fund_navs_funds_fund_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.FundPerformance", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Fund", null)
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fund_performances_funds_fund_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.IndexConstituent", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.MarketIndex", null)
                        .WithMany()
                        .HasForeignKey("IndexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_index_constituents_indices_index_id");

                    b.HasOne("Degerli.Persistence.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_index_constituents_instruments_instrument_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.IndexLevel", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.MarketIndex", null)
                        .WithMany()
                        .HasForeignKey("IndexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_index_levels_indices_index_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.Instrument", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Sector", null)
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_instruments_sectors_sector_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.KapDisclosure", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_kap_disclosures_instruments_instrument_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.MacroValue", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.MacroSeries", null)
                        .WithMany()
                        .HasForeignKey("SeriesCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_macro_values_macro_series_series_code");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.SavedScreen", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_screens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.Sector", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Sector", null)
                        .WithMany()
                        .HasForeignKey("ParentSectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sectors_sectors_parent_sector_id");
                });

            modelBuilder.Entity("Degerli.Persistence.Entities.SectorMetricMedian", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.Sector", null)
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sector_metric_medians_sectors_sector_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Degerli.Persistence.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Degerli.Persistence.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
