namespace Degerli.Persistence.Entities;

/// <summary>
/// DCF model baseline, versioned per build cycle (VAL §7; BR-VAL-008). Derived rows
/// generated by the Metrics Engine, not hand-edited content.
/// </summary>
public class DcfBaseline
{
    public long Id { get; set; }
    public long InstrumentId { get; set; }
    public int Version { get; set; }

    /// <summary>jsonb — the confirmed 8-parameter set.</summary>
    public string ParamsJson { get; set; } = null!;

    public DateOnly? BuildDate { get; set; }

    /// <summary>One active baseline per stock.</summary>
    public bool IsActive { get; set; }
}

/// <summary>
/// User-saved DCF scenario (VAL §7; FR-VAL-009/010). Duplicate name per
/// (user, instrument) is rejected by the unique constraint.
/// </summary>
public class DcfScenario
{
    public long Id { get; set; }

    /// <summary>FK to <c>asp_net_users</c>, cascade delete.</summary>
    public long UserId { get; set; }

    public long InstrumentId { get; set; }
    public string Name { get; set; } = null!;

    /// <summary>jsonb — same 8-parameter schema.</summary>
    public string ParamsJson { get; set; } = null!;

    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset UpdatedAt { get; set; }
}
